spring.application.name=cineflow-api

spring.datasource.url=jdbc:postgresql://localhost:5432/cineflow_db
spring.datasource.username=hygor_dev
spring.datasource.password=password123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html