openapi: 3.0.3
info:
  title: CineFlow API - Sistema de Gestão de Cinema
  description: |-
    API para controle de sessões, filmes e venda de ingressos. 
    Integração com RabbitMQ para processamento de vendas e Spring Security para proteção de endpoints administrativos.
  version: 1.0.0
servers:
  - url: http://localhost:8080/api/v1

tags:
  - name: Ingressos
    description: Operações de compra e consulta de status
  - name: Administrativo
    description: Gestão de salas, filmes e elenco (Atores/Papéis)

paths:
  /auth/cadastro:
    post:
      tags:
        - Auth
      summary: Criar uma nova conta de cliente
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UsuarioCadastro'
      responses:
        '201':
          description: Usuário criado com sucesso.
  /auth/login:
    post:
      tags:
        - Auth
      summary: Autentica o usuário e retorna um Token
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Login realizado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenResponse'
        '401':
          description: E-mail ou senha inválidos
  /ingressos:
    post:
      tags:
        - Ingressos
      summary: Realiza a compra de um ingresso
      description: Envia o pedido para uma fila no RabbitMQ. Retorna um protocolo para consulta.
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IngressoRequest'
      responses:
        '202':
          description: Aceito para processamento (Fila RabbitMQ)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatusProcessamento'
        '400':
          description: Sessão lotada ou encerrada
        '401':
          description: Não autenticado

  /admin/filmes:
    post:
      tags:
        - Administrativo
      summary: Cadastra um novo filme
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Filme'
      responses:
        '201':
          description: Filme criado com sucesso
        '403':
          description: Acesso negado (Requer ROLE_ADMIN)

components:
  schemas:
    UsuarioCadastro:
      type: object
      required:
        - nome
        - email
        - senha
      properties:
        nome:
          type: string
          example: "Hygor Dev"
        email:
          type: string
          format: email
          example: "hygor@email.com"
        senha:
          type: string
          format: password
          example: "senha123"

    LoginRequest:
      type: object
      required:
        - email
        - senha
      properties:
        email:
          type: string
          format: email
          example: "admin@cineflow.com"
        senha:
          type: string
          format: password
          example: "admin123"

    IngressoRequest:
      type: object
      properties:
        sessaoId:
          type: integer
          example: 101
        tipo:
          type: string
          enum: [INTEIRA, MEIA]
          example: MEIA
        clienteId:
          type: integer
          example: 550

    StatusProcessamento:
      type: object
      properties:
        protocolo:
          type: string
          example: "abc-123-xyz"
        status:
          type: string
          example: "PROCESSANDO"

    Filme:
      type: object
      properties:
        titulo:
          type: string
          example: "Batman"
        duracao:
          type: integer
          description: Duração em minutos
          example: 175
        generoId:
          type: integer
          example: 1

    TokenResponse:
      type: object
      properties:
        accessToken:
          type: string
          description: "O token JWT para ser usado no cabeçalho Authorization"
          example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
        tipo:
          type: string
          example: "Bearer"
        expiresIn:
          type: integer
          description: "Tempo para expirar em segundos"
          example: 3600

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT